server:
  port: 8902

#request header filter
#spring:
#  profiles:
#    active: add_request_header_route
#
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: add_request_header_route
#        uri: http://httpbin.org:80/get
#        filters:
#        - AddRequestHeader=X-Request-Foo, Bar
#        predicates:
#        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#  profiles: add_request_header_route

#重写路径Rewriter
#spring:
#  profiles:
#    active: rewritepath_route
#---
#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: rewritepath_route
#        uri: https://blog.csdn.net
#        predicates:
#        - Path=/feiyst/**
#        filters:
#        - RewritePath=/feiyst/(?<segment>.*), /$\{segment}
#  profiles: rewritepath_route

#自定义请求时间工厂类
spring:
  profiles:
    active: elapse_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: elapse_route
        uri: http://httpbin.org:80/get
        filters:
        - RequestTime=true
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: elapse_route