server:
  port: 8763

spring:
  profiles: peer1

eureka:
  instance:
    preferIpAddress: true
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/