server:
  port: 8762

spring:
  profiles: peer2

eureka:
  instance:
    preferIpAddress: true
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8763/eureka/

